# Generated by Django 4.2 on 2023-12-19 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itregistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='credit',
            field=models.SmallIntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='module',
            name='modulename',
            field=models.CharField(default='Computing', max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
