# Generated by Django 5.0 on 2023-12-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itregistration', '0002_remove_module_type_course_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='modules',
        ),
    ]
